# [options]
# admin_passwd = $pbkdf2-sha512$600000$bY0RYowRYswZY4wR4pxzLg$O4KTx8YiMoO39W28JwQtsNpzDziJS7ejcdMA5wfep8udZO2YdirBscdx5rUgNMe05/Erulmqacs5.RaW.mYq5A
# db_host = host.docker.internal
# db_port = 5432
# db_user = odoo
# db_password = 1441
# db_sslmode = disable
# addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
# http_port = 8069
# logfile = logs/odoo/odoo.log
# list_db = True

[options]
admin_passwd = 1234

db_host = db
db_port = 5432
db_user = odoo
db_password = odoo

db_sslmode = disable

addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
http_port = 8069
list_db = True    



# dwdasdqx